<?php

namespace AppBundle\Repository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
